kind: PersistentVolume
apiVersion: v1
metadata:
  name: database-persistent-volume
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /home/vncuser/docker/complex/data